### ISSUE TITLE
Can't make it work on iOS

### ISSUE THREAD

**Issue by franskjv** [ilteoood/flutter_i18n#58]
Hi, I'm trying to use the package and it's working OK on Android. But in iOS simulator it only gets en_US locale. I've changed the settings to another languages but no lucky. Even deploying in Release Mode for my iOS device (in Portuguese) it still uses the en locale. Any hint on what should be done? 

Here my Flutter Doctor:

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-BR)
    • Flutter version 1.12.13+hotfix.5 at /Users/franklin/Development/flutter
    • Framework revision 27321ebbad (3 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/franklin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • iPhone do Franklin • 8ca28e9db21289c970d810c3625aa017c • ios • iOS 13.3
    • iPhone 11 Pro Max  • 29823942-BC97-4196-B74D-A03C680     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```

And my main.dart

```
Future main() async {
  final FlutterI18nDelegate flutterI18nDelegate = FlutterI18nDelegate(
    useCountryCode: false, 
    fallbackFile: 'en',
    path: 'assets/flutter_i18n',
  );
  WidgetsFlutterBinding.ensureInitialized();
  await flutterI18nDelegate.load(null);
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp])
      .then((_) {
    runApp(new MyApp(flutterI18nDelegate));
  });
}

class MyApp extends StatelessWidget {
  FlutterI18nDelegate flutterI18nDelegate;

  MyApp(this.flutterI18nDelegate);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        appBarTheme: AppBarTheme(brightness: Brightness.light),
        primaryColor: Colors.white,
        scaffoldBackgroundColor: Colors.white,
        accentColor: kMainBlue,
        primaryTextTheme: TextTheme(
          title: TextStyle(
              fontFamily: 'Inter',
              fontWeight: FontWeight.w700,
              letterSpacing: 1.0),
        ),
      ),
      initialRoute: SplashScreen.id,
      routes: {
        LoginScreen.id: (context) => LoginScreen(),
        RegistrationScreen.id: (context) => RegistrationScreen(),
        HomeScreen.id: (context) => HomeScreen(),
        SplashScreen.id: (context) => SplashScreen(),
      },
      localizationsDelegates: [
        flutterI18nDelegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate
      ],
    );
  }
}
```
Thanks!

**Comment by ilteoood** [comment]
Hi,
I know that there's a known problem with system locale and Flutter and I think that is related only to the iOS emulator.
As workaround, I suggest you to:
1) Open the Info.plist; you can find it under 

> your_app_folder/ios/Runner/Info.plist
2) Add to this file the languages that you want to support, for example:
```
<key>CFBundleLocalizations</key>
<array>
	<string>English</string>
	<string>Italian</string>
	<string>es</string>
</array>
```
3) Delete all the other device languages, as I did in this screenshot.
<img width="336" alt="Screenshot 2019-12-29 at 16 13 36" src="https://user-images.githubusercontent.com/6383527/71558685-3308f300-2a56-11ea-84ce-7dfe77019726.png">

With the configuration above, you'll have: it_US

**Comment by franskjv** [comment]
Hey, thanks for the response. Actually, I did that:

```
	<key>CFBundleLocalizations</key>
	<array>
		<string>English</string>
		<string>pt</string>
		<string>es</string>
		<string>fr</string>
		<string>de</string>
	</array>
```
 and

<img width="407" alt="Screen Shot 2019-12-29 at 13 02 03" src="https://user-images.githubusercontent.com/4266955/71559339-9174a800-2a3b-11ea-8165-5f3a5108da60.png">

But I still get the app in English.

I'll keep trying (...)

Thanks.

**Comment by ilteoood** [comment]
Have you tried, after that, to launch the command:
`flutter clean`

Is used to force the iOS build to discard the previous .plist and use the new one.
Btw, I suggest you to use the newest version (0.8.3) that I've just published in order to have debugging messages in development mode!

**Comment by franskjv** [comment]
Yes, I do a ```flutter clean``` after those changes. I'll update the package. The intriguing part is that if I install in my device, buiding in Release Mode, even with my phone in Portuguese, it gets English. Probably it's not an issue with the Simulator, but with the platform. Thanks anyway!

**Comment by franskjv** [comment]
I don't know the correlation, but after I went to the ios folder and did a ```pod update``` and a ```flutter clean``` I rebuilt the app for the iOS Simulator and got English... I pressed ```Hot Reload``` and bang: Portuguese. I saw you put some debug messages and I got 3 times: 
```
flutter: The system locale is pt_BR
flutter: The current locale is pt_BR
flutter: JSON file loaded for pt
```
 Now, always after the ```Hot Reload``` I get the correct locale. Sadly, in Release Mode for my iOS device, I'm still getting english locale.

Trying to debug the source of the Locale, I put this line to get the user's language:
```print(Localizations.localeOf(context));```
from: [https://flutter.dev/docs/development/accessibility-and-localization/internationalization#tracking-the-locale-the-locale-class-and-the-localizations-widget](url)

But with this line I aways get en_US. Maybe it can help  to figure out what's going on.

Thanks again, and happy new year.

**Comment by franskjv** [comment]
I think I got the problem:

When the app is initialised, Flutter doesn't have the Locale from iOS platform yet. So the locale is null, and the algorithm just responds with the fallback language which is english.  (From this [Flutter issue](https://github.com/flutter/flutter/issues/24064)) However, if you do a Hot Restart, Flutter will have the correct locale from iOS.

So, I'm thinking how to work on that. Some possibilities:

1. To use a package like [devicelocale](https://pub.dev/packages/devicelocale) to get the locale asynchronously. 
2. Try to localize the app from another point in the lifecycle instead of the main.dart, as if the user wanted to change locale "manually".

If you guys have any thoughts I'd appreciate.

Thanks!

**Comment by ilteoood** [comment]
What if you combine the two option that you provided?
I mean: force the language after the main, but use the findCurrentLocale async function provided by flutter to do it. Is the same that I use inside the library

**Comment by franskjv** [comment]
I found an ugly workaround to wait until iOS responds with a locale. If you have any comments I would be grateful:

```
Future main() async {
  final FlutterI18nDelegate flutterI18nDelegate = FlutterI18nDelegate(
    useCountryCode: false,
    fallbackFile: 'en',
    path: 'assets/flutter_i18n',
  );
  WidgetsFlutterBinding.ensureInitialized();
  //This is the UGLY workaround
  while (ui.window.locale == null) {
    await Future.delayed(const Duration(milliseconds: 1));
  }
  await flutterI18nDelegate.load(null);
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp])
      .then((_) {
    runApp(new myApp(flutterI18nDelegate));
  });
}
```

**Comment by FabianGuerreroMaureira** [comment]
I got the same issue in a real device, iPhone 11 with iOS 13, i have just two language: Spanish and English, but in device always get English language, even if i set the device with Spanish language only.

**Comment by ilteoood** [comment]
@franskjv 
I've pushed on master (but not published on pub) a new info message under the load method.
As you can see, with a restored simulator, you have 2 messages:

> flutter: [flutter_i18n INFO]: New locale: null
> flutter: [flutter_i18n INFO]: New locale: en_US

It means that, at start, Flutter doesn't have any locale (as you correctly supposed), but after that the framework ask me to load the en_US locale.

I'm considering to watch the [ui.window.locale](https://api.flutter.dev/flutter/dart-ui/Window/locale.html), just have to figure out how to do it properly...

**Comment by Gabrielhn** [comment]
@franskjv 
@ilteoood 
Having the same issue here but not using the i18n pkg. (I'm using flutter_localizations). 
So it's really seems to be a core flutter related problem to load te locale "in-time"

I've constructed my own AppLocalizations.delegate containing the "load" method to translate the strings. For now not treating null returns from localeResolutionCallback, as the first messages.

Main.dart:
```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamProvider<FirebaseUser>.value(
      value: AuthService().uid,
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        title: appName,
        routes: routes,
        home: Wrapper(),
        supportedLocales: [
          const Locale('en', 'US'),
          const Locale('pt', 'BR'),
        ],
        localizationsDelegates: [
          AppLocalizations.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],
        localeResolutionCallback: (locale, supportedLocales) {
          // Check if the current device locale is supported
          for (var supportedLocale in supportedLocales) {
            if (supportedLocale.languageCode == locale.languageCode && supportedLocale.countryCode == locale.countryCode) {
              return supportedLocale;
            }
          }
          // If the locale of the device is not supported, use the first one
          // from the list (English, in this case).
          return supportedLocales.first;
        },
      ),
    );
  }
}
```

appLocalizations.dart:

```dart
class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  Map<String, String> _localizedStrings;

  Future<bool> load() async {
    String jsonString = await rootBundle
        .loadString('lib/assets/lang/${locale.languageCode}.json');
    Map<String, dynamic> jsonMap = json.decode(jsonString);

    _localizedStrings = jsonMap.map((key, value) {
      return MapEntry(key, value.toString());
    });

    return true;
  }

  String translate(String key) {
    return _localizedStrings[key];
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['pt', 'en'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    AppLocalizations localizations = new AppLocalizations(locale);
    await localizations.load();
    return localizations;
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

String lang(String text, BuildContext context) {
  return AppLocalizations.of(context).translate(text);
}
```

**Comment by ilteoood** [comment]
Hi everyone,
can you please test the code in this branch:
https://github.com/ilteoood/flutter_i18n/tree/fix_locale_ios

And tell me if for you is ok?
Matteo

**Comment by franskjv** [comment]
Hey Matteo, thanks for the response.
The first test I did, (after a flutter clean) the app opened in English, and after a few seconds it changed to Portuguese. 
```
flutter: [flutter_i18n INFO]: New locale: null
flutter: [flutter_i18n INFO]: The system locale is en_US
flutter: [flutter_i18n INFO]: The current locale is en_US
flutter: [flutter_i18n INFO]: JSON file loaded for en
flutter: [flutter_i18n INFO]: New locale: null
flutter: [flutter_i18n INFO]: The system locale is en_US
flutter: [flutter_i18n INFO]: The current locale is en_US
flutter: [flutter_i18n INFO]: JSON file loaded for en
flutter: [flutter_i18n INFO]: New locale: pt_BR
flutter: [flutter_i18n INFO]: The system locale is pt_BR
flutter: [flutter_i18n INFO]: The current locale is pt_BR
flutter: [flutter_i18n INFO]: JSON file loaded for pt
```
The second time you run the app, it goes english only:

```
flutter: [flutter_i18n INFO]: JSON file loaded for en
Syncing files to device iPhone 11 Pro Max...
flutter: [flutter_i18n INFO]: New locale: null
flutter: [flutter_i18n INFO]: The system locale is en_US
flutter: [flutter_i18n INFO]: The current locale is en_US
flutter: [flutter_i18n INFO]: JSON file loaded for en
```
Thanks!

**Comment by ilteoood** [comment]
That's really strange.
With a formatted simulator and without any edit to the pods, I've configured the device like this:
![image](https://user-images.githubusercontent.com/6383527/72670732-64675400-3a41-11ea-86d5-987598cfc2d0.png)

And the behavior is the expected one:
```sh
Syncing files to device iPhone 11 Pro Max...                            
 7,924ms (!)                                       

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on iPhone 11 Pro Max is available at: http://127.0.0.1:49565/4DAWgal0bWk=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".

Initializing hot reload...                                              
Reloaded 1 of 552 libraries in 193ms.

Performing hot restart...                                               
Restarted application in 1,162ms.
flutter: [flutter_i18n INFO]: New locale: it_US
flutter: [flutter_i18n INFO]: The system locale is it_US
flutter: [flutter_i18n INFO]: The current locale is it_US
flutter: [flutter_i18n INFO]: JSON file loaded for it
flutter: [flutter_i18n INFO]: New locale: it_US

Performing hot restart...                                               
Restarted application in 1,041ms.
flutter: [flutter_i18n INFO]: New locale: it_US
flutter: [flutter_i18n INFO]: The system locale is it_US
flutter: [flutter_i18n INFO]: The current locale is it_US
flutter: [flutter_i18n INFO]: JSON file loaded for it
flutter: [flutter_i18n INFO]: New locale: it_US
```

**Comment by ilteoood** [comment]
BTW, on the same branch (_fix_locale_ios_) I did a new push.
Can you take another test please?

Matteo

**Comment by franskjv** [comment]
Hey Matteo,

let's do it:
<img width="406" alt="Screen Shot 2020-01-19 at 10 34 50" src="https://user-images.githubusercontent.com/4266955/72682036-00c44180-3aa8-11ea-9a83-f27c0ac77465.png">

First build: (it worked)
```
flutter: [flutter_i18n INFO]: New locale: null
flutter: [flutter_i18n INFO]: The system locale is null
flutter: [flutter_i18n DEBUG]: Error loading translation RangeError (index): Invalid value: Only valid value is 0: 1
flutter: [flutter_i18n INFO]: JSON file loaded for en
flutter: [flutter_i18n INFO]: New locale: pt_BR
flutter: [flutter_i18n INFO]: The system locale is pt_BR
flutter: [flutter_i18n INFO]: The current locale is pt_BR
flutter: [flutter_i18n INFO]: JSON file loaded for pt
flutter: [flutter_i18n INFO]: New locale: pt_BR
```
Hot restart: (worked)
```
Performing hot restart...
Syncing files to device iPhone 11 Pro Max...
Restarted application in 968ms.
flutter: [flutter_i18n INFO]: New locale: pt_BR
flutter: [flutter_i18n INFO]: The system locale is pt_BR
flutter: [flutter_i18n INFO]: The current locale is pt_BR
flutter: [flutter_i18n INFO]: JSON file loaded for pt
flutter: [flutter_i18n INFO]: New locale: pt_BR
flutter: [flutter_i18n INFO]: New locale: pt_BR
```
Second build: (it started in English. After a few moments, it changed to Portuguese)
```
Xcode build done.                                           24.4s
flutter: [flutter_i18n INFO]: New locale: null
flutter: [flutter_i18n INFO]: The system locale is null
flutter: [flutter_i18n DEBUG]: Error loading translation RangeError (index): Invalid value: Only valid value is 0: 1
flutter: [flutter_i18n INFO]: JSON file loaded for en
Syncing files to device iPhone 11 Pro Max...
flutter: [flutter_i18n INFO]: New locale: null
flutter: [flutter_i18n INFO]: New locale: pt_BR
flutter: [flutter_i18n INFO]: The system locale is pt_BR
flutter: [flutter_i18n INFO]: The current locale is pt_BR
flutter: [flutter_i18n INFO]: JSON file loaded for pt
```
Third build in release mode for a physical iOS device: (didn't work)

Thanks.
Franklin

**Comment by ilteoood** [comment]
Hi,
I'll take another look at this. Seems that Flutter can't return the current language (I've also tried with your approch of window.locale) and I can't test on a real iOS device...

**Comment by brunovsiqueira** [comment]
Same problem here. Did you guys find any solution?

**Comment by ilteoood** [comment]
Unfortunately not.
I don't have a real iOS device to make some tests.
Did you tried the fix_locale_ios branch to see what happens?

**Comment by brunovsiqueira** [comment]
No, is it on this project? Not in master?

**Comment by ilteoood** [comment]
Yes, is another branch of this project, different from master.

**Comment by ilteoood** [comment]
Hi @franskjv,
can you try [this](https://github.com/flutter/flutter/issues/14128#issuecomment-591502528) solution, as suggested in [this](https://github.com/flutter/flutter/issues/14128) issue?

**Comment by joaovirgili** [comment]
I'm facing this issue you mentioned above.

flutter: [flutter_i18n INFO]: New locale: en_US
flutter: [flutter_i18n INFO]: The system locale is en
flutter: [flutter_i18n DEBUG]: Error loading translation RangeError (index): Invalid value: Only valid value is 0: 1
flutter: [flutter_i18n INFO]: JSON file loaded for pt_BR

Even getting the system locale "en" it keeps choosing the fallbackFilte setted as "pt_BR".

**Comment by ilteoood** [comment]
Hi @joaovirgili,
that issue has been fixed with version 0.10.1.
Please, try again!

**Comment by joaovirgili** [comment]
@ilteoood worked. Thanks!

**Comment by franskjv** [comment]
> Hi @franskjv,
> can you try [this](https://github.com/flutter/flutter/issues/14128#issuecomment-591502528) solution, as suggested in [this](https://github.com/flutter/flutter/issues/14128) issue?

Hey @ilteoood. I have tested that. Actually, my Info.plist has all the languages I support.
<img width="397" alt="Screen Shot 2020-03-14 at 11 51 33" src="https://user-images.githubusercontent.com/4266955/76684356-2f632200-65ea-11ea-96a6-ce35e9530ec4.png">

 But the only way I get the correct language response from Flutter still is with that loop in main.dart:
```
while (ui.window.locale == null) {
    await Future.delayed(const Duration(milliseconds: 1));
  }
```

Thanks!

**Comment by ilteoood** [comment]
With the latest version and the support to supportedLocales, this should be fixed now.
